steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$REGION-docker.pkg.dev/$PROJECT_ID/containers/appointease:$COMMIT_SHA', '.']
  
  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$REGION-docker.pkg.dev/$PROJECT_ID/containers/appointease:$COMMIT_SHA']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'appointease'
    - '--image'
    - '$REGION-docker.pkg.dev/$PROJECT_ID/containers/appointease:$COMMIT_SHA'
    - '--region'
    - '$REGION'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--port=8080'
    - '--set-env-vars=NODE_ENV=production'
    - '--set-secrets=DATABASE_URL=DATABASE_URL:latest'

substitutions:
  _REGION: southamerica-west1 # default value
  
images:
  - '$REGION-docker.pkg.dev/$PROJECT_ID/containers/appointease:$COMMIT_SHA'