steps:
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'appointease'
      - '--source'
      - '.'
      - '--region=southamerica-west1'
      - '--platform=managed'
      - '--allow-unauthenticated'      
      - '--set-env-vars=NODE_ENV=production,DEBUG=express:*'